secrets:
  enabled: true

service:
  type: ClusterIP
  port: 3080
  targetPort: 3080
  serviceName: qtest-launch-service


ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
    - launch.qtest.local
  paths:
    - path: /
      pathType: Prefix
      backendServiceName: qtest-launch-service
      backendPort: 3080

  extraPaths: []
  tls:
    - hosts:
        - launch.qtest.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
