# Default values for qtest-launch app.
namespace:
  name: qtest
reloader:
  enabled: false
secrets:
  enabled: true
image:
  repository: qasymphony/launch
  pullPolicy: IfNotPresent
  tag: "10.5.2"
deployment:
  annotations: {}
service:
  type: LoadBalancer
  port: 3080
  targetPort: 3080
  serviceName: qtest-launch-service
qTestLaunch:
  qTestLaunchDBName: qtest
  qTestLaunchDBUserName: postgres
  qTestLaunchDBPwd: Y2hhbmdlbWU=
  qTestLaunchDBHostName: postgres.local
  qTestLaunchRootURL: https://launch.local
  qTestLaunchQTestURL: https://nephele.qtest.local
  qTestLaunchNodeTLSRejectUnAuthorized: "0"
  qTestLaunchTCPWD: "qTest"
  qTestLaunchPort: "3080"
#### Ingress/IngressClass (> K8s 1.18-1.22+) #####
ingressClass:
  enabled: true
  labels: {}
  controller: ingress.k8s.aws/alb
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""
ingress:
  enabled: true
  name: qtest-launch-ingress
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations: {}
    # canary-by-header: []
    # canary-by-header-pattern: []
  hosts:
    host: svc.qtest.com
  paths: []
  extraPaths:
    - path: /*
      pathType: ImplementationSpecific
  tls: []
  # - secretName: qtest-svc-tls
  #   hosts:
  #     - svc.qtest.com
  https: false
# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"
# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /health-check
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi
limitRange:
  enabled: false
resourceQuota:
  enabled: false
