apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-insights-etl-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qTestInsightsEtl
data:
  LOG_PATH: "{{ .Values.qTestInsightsEtl.qTestInsightsProxyEnabled }}"
  QTEST_DB_NAME: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlDBName }}"
  QTEST_DB_HOST: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlDBHost }}"
  QTEST_DB_USER: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlDBUser }}"
  WRITE_QTEST_DB_NAME: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlWriteQTestDBName }}"
  WRITE_QTEST_DB_HOST: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlWriteQTestDBHost }}"
  WRITE_QTEST_DB_USER: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlWriteQTestDBUser }}"
  SESSIONS_DB_NAME: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlSessionDBName }}"
  SESSIONS_DB_HOST: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlSessionDBHost }}"
  SESSIONS_DB_USER: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlSessionDBUser }}"
  UPDATEDB: "true"
