{{- $existingImageCredentials := .Values.imageCredentials.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-insights-etl
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: 3
  {{- if .Values.rollouts.enabled }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: qtest-insights-etl
  template:
    metadata:
      labels:
        app: qtest-insights-etl
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{ if .Values.imageCredentials.enabled }}
      {{ if .Values.imageCredentials.existingImageCredentials }}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{ else }}
      imagePullSecrets:
        - name: {{ $imageCredentials }}
      {{- end }}
    {{- end }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      initContainers:
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
{{- if .Values.extraArgs }}
          args:
{{- with .Values.extraArgs }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.autoscaling.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.autoscaling.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.autoscaling.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: qtest-insights-etl-configmap
          env:
            - name: QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: WRITE_QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: SESSIONS_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sessionsName }}
                  key: client.jdbc.postgres.password
            - name: WRITE_SESSIONS_DB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sessionsName }}
                  key: client.jdbc.postgres.password
{{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: qtest-insights-etl-logs
              mountPath: /usr/local/insights-etl/logs
{{- with .Values.extraVolumeMounts }}
{{ toYaml . | indent 12 }}
{{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: qtest-insights-etl-logs
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-insights-etl.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- with .Values.extraVolumes }}
{{ toYaml . | indent 8 }}
{{- end }}

