{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  QTEST_DB_PW: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlDBPassword }}"
  WRITE_QTEST_DB_PW: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlWriteQTestDBPassword }}"
  SESSIONS_DB_PW: "{{ .Values.qTestInsightsEtl.qTestInsightsEtlSessionDBPassword }}"
  WRITE_SESSIONS_DB_PW: "{{ .Values.qTestInsightsEtl.writeSessionsDBPassword }}"
kind: Secret
metadata:
  name: qtest-insights-etl-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
{{- end -}}
