helm-extra-args: --timeout 300s
check-version-increment: false
debug: true
target-branch: main
chart-dirs:
  - Charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - reloader=https://stakater.github.io/stakater-charts
remote: origin