apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-insights
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-insights
  template:
    metadata:
      labels:
        app: qtest-insights
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      {{- if .Values.securityContext }}
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
          {{- if .Values.qTestInsights.serverAppSSLRequired }}
           {{- toYaml .Values.autoscaling.livenessSslProbe | nindent 12 }}
          {{- else }}
           {{- toYaml .Values.autoscaling.livenessProbe | nindent 12 }}
          {{- end }}
          readinessProbe:
          {{- if .Values.qTestInsights.serverAppSSLRequired }}
           {{- toYaml .Values.autoscaling.readinessSslProbe | nindent 12 }}
          {{- else }}
           {{- toYaml .Values.autoscaling.readinessProbe | nindent 12 }}
          {{- end }}
          startupProbe:
          {{- if .Values.qTestInsights.serverAppSSLRequired }}
           {{- toYaml .Values.autoscaling.startupSslProbe | nindent 12 }}
          {{- else }}
           {{- toYaml .Values.autoscaling.startupProbe | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
          {{- if .Values.qTestInsights.serverAppSSLRequired }}
          - containerPort: {{ .Values.service.targetHttpsPort }}
            name: https
            protocol: TCP
          {{- else }}
          - containerPort: {{ .Values.service.targetPort }}
            name: http
            protocol: TCP
          {{- end }}
          envFrom:
            - configMapRef:
                name: qtest-insights-configmap
          env:
            - name: QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: client.jdbc.postgres.password
            - name: WRITE_QTEST_DB_PW
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: client.jdbc.postgres.password
            - name: SESSIONS_DB_PW
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: client.jdbc.postgres.password
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: mail.password
          volumeMounts:
            - name: qtest-insights
              mountPath: /usr/local/tomcat/logs/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/ErrorLog/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/SavedDashboards/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/SavedBookmarks/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/CustomReports/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/rdDataCache
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/rdDownload
            {{- if .Values.qTestInsights.serverAppSSLRequired }}
            - name: qtest-insights-secret-ssl-volume
              mountPath: {{ .Values.qTestInsights.server.sslMountPath }}
              readOnly: true
            {{- end }}
      volumes:
        - name: qtest-insights
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-insights.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.qTestInsights.serverAppSSLRequired }}
        - name: qtest-insights-secret-ssl-volume
          secret:
            secretName: qtest-ssl-root-secret
        {{- end }}
