apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-insights
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: qtest-insights
  template:
    metadata:
      labels:
        app: qtest-insights
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: qtest-insights-configmap
            - secretRef:
                name: qtest-insights-secret
          volumeMounts:
            - name: qtest-insights
              mountPath: /usr/local/tomcat/logs/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/ErrorLog/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/SavedDashboards/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/SavedBookmarks/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/CustomReports/
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/rdDataCache
            - name: qtest-insights
              mountPath: /usr/local/tomcat/webapps/ROOT/rdDownload
      volumes:
        - name: qtest-insights
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-insights.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
