{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  QTEST_DB_PW: "{{ .Values.qTestInsights.qTestInsightsDBPassword }}"
  WRITE_QTEST_DB_PW: "{{ .Values.qTestInsights.qTestInsightsWriteQTestDBPassword }}"
  SESSIONS_DB_PW: "{{ .Values.qTestInsights.qTestInsightsSessionDBPassword }}"
kind: Secret
metadata:
  name: qtest-insights-secret
type: Opaque
{{- end -}}
