apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qtest-insights
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-insights.chart" . }}
spec:
  ports:
  {{- if .Values.qTestInsights.serverAppSSLRequired }}
  - name: https
    protocol: TCP
    port: {{ .Values.service.targetHttpsPort }}
    targetPort: {{ .Values.service.targetHttpsPort }}
  {{- else }}
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  selector:
    app: qtest-insights
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
---
{{- if .Values.rollouts.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}-canary
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qtest-insights
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "qtest-insights.chart" . }}
spec:
  ports:
  {{- if .Values.qTestInsights.serverAppSSLRequired }}
  - name: https
    protocol: TCP
    port: {{ .Values.service.targetHttpsPort }}
    targetPort: {{ .Values.service.targetHttpsPort }}
  {{- else }}
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  selector:
    app: qtest-insights
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- end }}
