secrets:
  enabled: true

service:
  type: ClusterIP
  port: 6080
  targetPort: 6080
  serviceName: qtest-scenario-service
  annotations: {}

ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
  - scenario.qtest.local
  paths:
    - path: /
      pathType: Prefix 
      backendServiceName: qtest-scenario-service
      backendPort: 6080

  extraPaths: []

  tls:
  - hosts:
    - scenario.qtest.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
