# Default values for scenario App.
namespace:
  name: qtest
reloader:
  enabled: false
secrets:
  enabled: true
image:
  repository: qasymphony/scenario
  pullPolicy: IfNotPresent
  tag: "3.3.6"
deployment:
  annotations: {}
service:
  type: LoadBalancer
  port: 6080
  targetPort: 6080
  serviceName: qtest-scenario-service
  annotations: {}
qTestScenario:
  qTestScenarioDBName: scenario
  qTestScenarioDBUserName: postgres
  qTestScenarioDBHostName: host.docker.internal
  postgresDBPassword:
    secret: qtest-manager-secret
  qTestScenarioPort: "6080"
  qTestScenarioLocalBaseURL: https://scenario.local
  qTestScenarioNodeTLSRejectUnAuthorized: "0"
  qTestScenarioNodeEnvironment: production
  qTestScenarioRefreshTokenSecret: ""
  qTestScenarioAppKeyDescriptor: ""
  qTestScenarioQTestURL: https://nephele.qtest.local
  qTestScenarioDBSSLEnable: false
  qTestScenarioDBSSLMountPath: ""
  qTestScenarioDBSSL: ""
  qTestScenarioDBCRT: ""
#### Ingress/IngressClass (> K8s 1.18-1.22+) #####
ingressClass:
  enabled: true
  labels: {}
  controller: ingress.k8s.aws/alb
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""
ingress:
  enabled: true
  name: scenario-nginx
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations: {}
  hosts:
    - host: qtest.svc.com
  paths: []
  extraPaths:
    - path: /*
      backendServiceName: qtest-scenario-service
      pathType: ImplementationSpecific
      backendPort: 6080
  tls: []
  # - secretName: qtest-svc-tls
  #   hosts:
  #     - svc.qtest.com
  https: false
# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledValues: RequestsAndLimits
# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /atlassian-connect.json
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi
limitRange:
  enabled: false
resourceQuota:
  enabled: false
