apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-parameters-configmap
  labels:
    app: qTestParameters
data:
  qTestParametersDBName: "{{ .Values.qTestParameters.qTestParametersDBName }}"
  qTestParametersDBUserName: "{{ .Values.qTestParameters.qTestParametersDBUserName }}"
  qTestParametersDBPwd: "{{ .Values.qTestParameters.qTestParametersDBPwd }}"
  qTestParametersDBHostName: "{{ .Values.qTestParameters.qTestParametersDBHostName }}"
  qTestParametersQTestHost: "{{ .Values.qTestParameters.qTestParametersQTestHost }}"
  qTestParametersNodeTLSRejectUnAuthorized: "{{ .Values.qTestParameters.qTestParametersNodeTLSRejectUnAuthorized }}"
  qTestParametersNodeEnv: "{{ .Values.qTestParameters.qTestParametersNodeEnv }}"
  qTestParametersPort: "{{ .Values.qTestParameters.qTestParametersPort }}"