{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestParametersDBPWD: "{{ .Values.qTestParameters.qTestParametersDBPwd }}"
kind: Secret
metadata:
  name: qtest-parameters-secret
type: Opaque
{{- end -}}
