apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qtest-parameters
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    {{- if .Values.qTestParameters.qTestParametersSSLRequired }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.targetHttpsPort }}
      targetPort: {{ .Values.service.targetHttpsPort }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
  selector:
    app: qtest-parameters
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}