apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qtest-pulse.fullname" . }}-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qTestPulse
data:
  qTestPulseDBName: "{{ .Values.qTestPulse.qTestPulseDBName }}"
  qTestPulseDBUserName: "{{ .Values.qTestPulse.qTestPulseDBUserName }}"
  qTestPulseDBHostName: "{{ .Values.qTestPulse.qTestPulseDBHostName }}"
  qTestPulseRootURL: "{{ .Values.qTestPulse.qTestPulseRootURL }}"
  qTestPulseQTestURL: "{{ .Values.qTestPulse.qTestPulseQTestURL }}"
  qTestPulseScenarioURL: "{{ .Values.qTestPulse.qTestPulseScenarioURL }}"
  qTestPulseNodeTLSRejectUnAuthorized: "{{ .Values.qTestPulse.qTestPulseNodeTLSRejectUnAuthorized }}"
  qTestPulsePort: "{{ .Values.qTestPulse.qTestPulsePort }}"
  qTestPulseNodeEnv: "{{ .Values.qTestPulse.qTestPulseNodeEnv }}"
  qTestPulseType: "{{ .Values.qTestPulse.qTestPulseType }}"
  qtestPulseExecutorUrl: "{{ .Values.qTestPulse.qtestPulseExecutorUrl }}"
  swaggerUrl: "{{ .Values.qTestPulse.swaggerUrl }}"