{{- $sslCert := printf "%s/tls.crt" .Values.qTestPulse.qTestPulseSSLMountPath -}}
{{- $sslKey := printf "%s/tls.key" .Values.qTestPulse.qTestPulseSSLMountPath -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qtest-pulse.fullname" . }}-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qTestPulse
data:
  qTestPulseDBName: "{{ .Values.qTestPulse.qTestPulseDBName }}"
  qTestPulseDBUserName: "{{ .Values.qTestPulse.qTestPulseDBUserName }}"
  qTestPulseDBHostName: "{{ .Values.qTestPulse.qTestPulseDBHostName }}"
  qTestPulseDBPort: "{{ .Values.qTestPulse.qTestPulseDBPort }}"
  qTestPulseRootURL: "{{ .Values.qTestPulse.qTestPulseRootURL }}"
  qTestPulseQTestURL: "{{ .Values.qTestPulse.qTestPulseQTestURL }}"
  qTestPulseScenarioURL: "{{ .Values.qTestPulse.qTestPulseScenarioURL }}"
  qTestPulseNodeTLSRejectUnAuthorized: "{{ .Values.qTestPulse.qTestPulseNodeTLSRejectUnAuthorized }}"
  qTestPulseNodeEnv: "{{ .Values.qTestPulse.qTestPulseNodeEnv }}"
  qTestPulseType: "{{ .Values.qTestPulse.qTestPulseType }}"
  qtestPulseExecutorUrl: "{{ .Values.qTestPulse.qtestPulseExecutorUrl }}"
  swaggerUrl: "{{ .Values.qTestPulse.swaggerUrl }}"
  qTestPulseIsSSLRequired: "{{ .Values.qTestPulse.qTestPulseSSLRequired }}"
  {{- if .Values.qTestPulse.qTestPulseSSLRequired }}
  qTestPulseSSLCert: "{{ $sslCert }}"
  qTestPulseSSLKey: "{{ $sslKey }}"
  qTestPulsePort: "{{ .Values.service.targetHttpsPort }}"
  {{- else }}
  qTestPulsePort: "{{ .Values.service.targetPort }}"
  {{- end -}}
