apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-pulse
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: qtest-pulse
  template:
    metadata:
      labels:
        app: qtest-pulse
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseNodeEnv
            - name: PULSE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseDBName
            - name: PULSE_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseDBUserName
            - name: PULSE_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: client.jdbc.postgres.password
            - name: PULSE_DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseDBHostName
            - name: PG_URL
              {{- if .Values.qTestPulse.qTestPulseDBSSLEnable }}
              value: {{ printf "postgresql://$(PULSE_DB_USERNAME):$(PULSE_DB_PWD)@$(PULSE_DB_HOSTNAME)/$(PULSE_DB_NAME)%s" .Values.qTestPulse.qTestPulseDBSSL }}
              {{- end }}
              {{- if not .Values.qTestPulse.qTestPulseDBSSLEnable }}
              value: {{ printf "postgresql://$(PULSE_DB_USERNAME):$(PULSE_DB_PWD)@$(PULSE_DB_HOSTNAME)/$(PULSE_DB_NAME)" }}
              {{- end }}
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulsePort
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseNodeTLSRejectUnAuthorized
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseRootURL
            - name: QTEST_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseQTestURL
            - name: SCENARIO_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-pulse-configmap
                  key: qTestPulseScenarioURL
{{- if .Values.qTestPulse.qTestPulseDBSSLEnable }}
          volumeMounts:
          - name: qtest-db-secret-volume
            mountPath: {{ .Values.qTestPulse.qTestPulseDBSSLMountPath }}
      volumes:
      - name: qtest-db-secret-volume
        secret:
          secretName: qtest-db-root-secret
{{- end -}}