{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestPulseDBPWD: "{{ .Values.qTestPulse.qTestPulseDBPwd }}"
kind: Secret
metadata:
  name: qtest-pulse-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
{{- end -}}
