{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestPulseDBPWD: "{{ .Values.qTestPulse.qTestPulseDBPwd }}"
kind: Secret
metadata:
  name: qtest-pulse-secret
type: Opaque
{{- end -}}
