secrets:
  enabled: true

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  serviceName: qtest-insights-service


ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
    - insights.qtest.local
  paths:
    - path: /
      pathType: Prefix
      backendServiceName: qtest-insights-service
      backendPort: 8080

  extraPaths: []
  tls:
    - hosts:
        - insights.qtest.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
