# Default values for qtest-pulse-chart.
reloader:
  enabled: false

secrets:
  enabled: true

image:
  repository: qasymphony/pulse
  pullPolicy: IfNotPresent
  tag: "9.3.5"

deployment:
  annotations: {}

service:
  type: LoadBalancer
  port: 4080
  targetPort: 4080
  serviceName: qtest-pulse-service

qTestPulse:
  qTestPulseDBName: pulse
  qTestPulseDBUserName: postgres
  qTestPulseDBPwd: Y2hhbmdlbWU=
  qTestPulseDBHostName: postgres.local
  qTestPulsePort: "4080"
  qTestPulseNodeEnv: production
  qTestPulseRootURL: https://pulse.local
  qTestPulseQTestURL: https://nephele.qtest.local
  qTestPulseScenarioURL: https://scenario.local
  qTestPulseNodeTLSRejectUnAuthorized: "0"

#### Ingress/IngressClass (> K8s 1.18-1.22+) #####
ingressClass:
  enabled: true
  labels: {}
  controller: ingress.k8s.aws/alb
  isDefaultClass: true
  # Use to force a networking.k8s.io API Version for certain CI/CD applications. Ex. "v1"
  fallbackApiVersion: ""

ingress:
  enabled: true
  name: qtest-pulse-ingress
  labels: {}
  annotations: {}
  canary:
    annotationPrefix: ""
    annotations: {}
      # canary-by-header: []
      # canary-by-header-pattern: []
  hosts:
    host: svc.qtest.com

  paths: []

  extraPaths:
    - path: /*
      pathType: ImplementationSpecific

  tls:
    []
    # - secretName: qtest-svc-tls
    #   hosts:
    #     - svc.qtest.com
  https: false

# VPA values
vpaAutoscaling:
  enabled: false
  updatePolicy:
    updateMode: "Off"

# HPA values
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  healthApiPath: /
  periodSeconds: 30
  failureThreshold: 4
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85
