secrets:
  enabled: true

ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
  - nephele.qtest.local
  - qtestdev1.qtest.local
  tls:
  - secretName: qtest-tls-secret
    hosts:
    - nephele.qtest.local
    - qtestdev1.qtest.local

persistence:
  existingClaim: qtest-onpremise-pvc
  accessMode: ReadWriteOnce
  size: 10Gi