secrets:
  enabled: true

ingressClass:
  enabled: false
  controller: k8s.io/ingress-nginx

ingress:
  className: nginx
  hosts:
  - nephele.qtest.local
  - qtestdev1.qtest.local
  paths: []
  extraPaths:
    - path: /*
      pathType: Prefix
      backendServiceName: mgr-service
      backendPort: 8080
  tls:
  - secretName: qtest-tls-secret
    hosts:
    - nephele.qtest.local
    - qtestdev1.qtest.local

persistence:
  existingClaim: qtest-onpremise-pvc
  accessMode: ReadWriteOnce
  size: 10Gi

qTestManager:
  async:
    threadNo: 100
    maxCpu: 101
    databaseCpu: 101
  action:
    task:
      executor:
        poolSize: 2
  qtest:
    request:
      nonce:
        disabled: true
        mode: HighPrecision
  security:
    csrf:
      source:
        trust:
          pattern: ""
  cors:
    allowed:
      all: true
      domains: ""
  vera:
    auto:
      testrun:
        beta:
          clients: -1
  blobStorage:
    type: disk_storage
  s3:
    accessKey: ""
    secretKey: ""