apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-chart-resource-quota
spec:
  hard:
    limits.cpu: "12"
    limits.memory: 16Gi
    requests.cpu: "14.4"
    requests.memory: 13.6Gi
    pods: "16"
    persistentvolumeclaims: "25"
    requests.storage: "200Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-chart-limit-range
spec:
  limits:
    - max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: "0.85"
        memory: 0.85Gi
      default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
          cpu: "0.85"
          memory: 0.85Gi
      type: Container
