{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-chart-resource-quota
spec:
  hard:
    {{ .Values.resourceQuota.hard | toYaml | indent 4 | trim }}
---
{{- end }}
{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-chart-limit-range
spec:
  limits:
    {{ .Values.limitRange.limits | toYaml | indent 4 | trim }}
{{- end }}
