apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-chart-resource-quota
spec:
  hard:
    {{ .Values.resourceQuota | toYaml | indent 4 | trim }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-chart-limit-range
spec:
  limits:
    {{ .Values.limitRange | toYaml | indent 4 | trim }}
