apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-chart-resource-quota
spec:
  hard:
    limits.cpu: "48"
    limits.memory: 64Gi
    requests.cpu: "40.8"
    requests.memory: 54.4Gi
    pods: "20"
    persistentvolumeclaims: "25"
    requests.storage: "200Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-chart-limit-range
spec:
  limits:
    - max:
        cpu: "3"
        memory: 4Gi
      min:
        cpu: "1"
        memory: 2Gi
      default:
        cpu: "3"
        memory: 4Gi
      defaultRequest:
          cpu: "1"
          memory: 2Gi
      type: Container
