{{- $sslCert := printf "%s/tls.crt" .Values.qTestLaunch.qTestLaunchSSLMountPath -}}
{{- $sslKey := printf "%s/tls.key" .Values.qTestLaunch.qTestLaunchSSLMountPath -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-launch-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qtest-launch
data:
  qTestLaunchDBName: "{{ .Values.qTestLaunch.qTestLaunchDBName }}"
  qTestLaunchDBUserName: "{{ .Values.qTestLaunch.qTestLaunchDBUserName }}"
  qTestLaunchDBHostName: "{{ .Values.qTestLaunch.qTestLaunchDBHostName }}"
  qTestLaunchDBPort: "{{ .Values.qTestLaunch.qTestLaunchDBPort }}"
  qTestLaunchDeploymentEnv: "{{ .Values.qTestLaunch.qTestLaunchDeploymentEnv }}"
  qTestLaunchRootURL: "{{ .Values.qTestLaunch.qTestLaunchRootURL }}"
  qTestLaunchQTestURL: "{{ .Values.qTestLaunch.qTestLaunchQTestURL }}"
  qTestLaunchTCPWD: "{{ .Values.qTestLaunch.qTestLaunchTCPWD }}"
  qTestLaunchNodeTLSRejectUnAuthorized: "{{ .Values.qTestLaunch.qTestLaunchNodeTLSRejectUnAuthorized }}"
  qTestLaunchIsSSLRequired: "{{ .Values.qTestLaunch.qTestLaunchSSLRequired }}"
  {{- if .Values.qTestLaunch.qTestLaunchSSLRequired }}
  qTestLaunchSSLCert: "{{ $sslCert }}"
  qTestLaunchSSLKey: "{{ $sslKey }}"
  qTestLaunchPort: "{{ .Values.service.targetHttpsPort }}"
  {{- else }}
  qTestLaunchPort: "{{ .Values.service.targetPort }}"
  {{- end -}}
