{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestLaunchDBPWD: "{{ .Values.qTestLaunch.qTestLaunchDBPwd }}"
kind: Secret
metadata:
  name: qtest-launch-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
{{- end -}}
