{{- if .Values.vpaAutoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "qtest-launch.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-launch.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "qtest-launch.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
  resourcePolicy:
    {{- with .Values.vpaAutoscaling.resourcePolicy -}}
        {{- toYaml . | nindent 4 }}
    {{- end }}
      controlledResources: ["cpu", "memory"]
{{- end }}
