apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-session-configmap
  labels:
    app: qTestSession
data:
  qTestSessionJSHome: "{{ .Values.qTestSession.qTestSessionJSHome }}"
  qTestSessionNodeEnvironment: "{{ .Values.qTestSession.qTestSessionNodeEnvironment }}"
  qTestSessionPort: "{{ .Values.qTestSession.qTestSessionPort }}"
  qTestSessionDBName: "{{ .Values.qTestSession.qTestSessionDBName }}"
  qTestSessionDBUserName: "{{ .Values.qTestSession.qTestSessionDBUserName }}"
  qTestSessionDBHostName: "{{ .Values.qTestSession.qTestSessionDBHostName }}"
  QTestManagerHost: "{{ .Values.qTestSession.qTestManagerHost }}"
  qTestSessionMasterToken: "{{ .Values.qTestSession.qTestSessionMasterToken }}"
  qTestSessionStorageRootPath: "{{ .Values.qTestSession.qTestSessionStorageRootPath }}"
  qTestSessionClamavURL: "{{ .Values.qTestSession.qTestSessionClamavURL }}"
  qTestStorageBucketName: "{{ .Values.qTestSession.qTestStorageBucketName }}"
