{{- $existingImageCredentials := .Values.imageCredentials.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qtest-session.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.rollouts.enabled }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-session
  template:
    metadata:
      labels:
        app: qtest-session
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{ if .Values.imageCredentials.enabled }}
      {{ if .Values.imageCredentials.existingImageCredentials }}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{ else }}
      imagePullSecrets:
        - name: {{ $imageCredentials }}
      {{- end }}
    {{- end }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      initContainers:
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ template "qtest-session.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountsatoken }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
{{- if .Values.extraArgs }}
          args:
{{- with .Values.extraArgs }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          env:
            - name: SESSION_JS_HOME
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionJSHome
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionNodeEnvironment
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionDBName
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionDBUserName
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionDBHostName
            {{- if .Values.qTestSession.qTestSessionCustomSchemaEnable }}
            - name: DATABASE_SCHEMA_SESSION
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionCustomSchemaName
            {{- end }}   
            - name: DB_CONNECTION
              {{- if and (.Values.qTestSession.qTestSessionDBSSLEnable) (.Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)?schema=$(DATABASE_SCHEMA_SESSION)%s" .Values.qTestSession.qTestSessionDBSSL }}
              {{- end }}
              {{- if and (.Values.qTestSession.qTestSessionDBSSLEnable) (not .Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)%s" .Values.qTestSession.qTestSessionDBSSL }}
              {{- end }}
              {{- if and (not .Values.qTestSession.qTestSessionDBSSLEnable) (.Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)?schema=$(DATABASE_SCHEMA_SESSION)" }}
              {{- end }}
              {{- if and (not .Values.qTestSession.qTestSessionDBSSLEnable) (not .Values.qTestSession.qTestSessionCustomSchemaEnable)}}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)" }}
              {{- end }}
            - name: DATABASE_URL
              {{- if and (.Values.qTestSession.qTestSessionDBSSLEnable) (.Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)?schema=$(DATABASE_SCHEMA_SESSION)%s" .Values.qTestSession.qTestSessionDBSSL }}
              {{- end }}
              {{- if and (.Values.qTestSession.qTestSessionDBSSLEnable) (not .Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)%s" .Values.qTestSession.qTestSessionDBSSL }}
              {{- end }}
              {{- if and (not .Values.qTestSession.qTestSessionDBSSLEnable) (.Values.qTestSession.qTestSessionCustomSchemaEnable) }}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)?schema=$(DATABASE_SCHEMA_SESSION)" }}
              {{- end }}
              {{- if and (not .Values.qTestSession.qTestSessionDBSSLEnable) (not .Values.qTestSession.qTestSessionCustomSchemaEnable)}}
              value: {{ printf "postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_NAME)" }}
              {{- end }}
            - name: QTEST_HOST
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: QTestManagerHost
            - name: QTEST_MASTER_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionMasterToken
            - name: SESSION_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestStorageBucketName
            - name: SESSION_STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionStorageType
            - name: CLAMAV_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionClamavURL
            - name: SESSION_STORAGE_ROOT_PATH
              valueFrom:
                configMapKeyRef:
                  name: qtest-session-configmap
                  key: qTestSessionStorageRootPath
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.sessionsSecretKey }}
{{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
          - name: qtest-session-data
            mountPath: /usr/local/sessions-js/logs
          {{- if .Values.qTestSession.qTestSessionDBSSLEnable }}
          - name: qtest-db-secret-volume
            mountPath: {{ .Values.qTestSession.qTestSessionDBSSLMountPath }}
            readOnly: true
          {{- end }}
{{- with .Values.extraVolumeMounts }}
{{ toYaml . | indent 10 }}
{{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: qtest-session-data
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-session.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.qTestSession.qTestSessionDBSSLEnable }}
        - name: qtest-db-secret-volume
          secret:
            secretName: qtest-db-root-secret
        {{- end -}}
{{- with .Values.extraVolumes }}
{{ toYaml . | indent 8 }}
{{- end }}