{{- if .Values.rollouts.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "qtest-session.fullname" . }}-rollout
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  revisionHistoryLimit: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "qtest-session.fullname" . }}
  strategy:
   {{- with .Values.rollouts.strategy -}}
      {{- toYaml . | nindent 4 }}
   {{- end }} 
      canaryService: {{ .Values.service.serviceName }}-canary
      stableService: {{ .Values.service.serviceName }}
      trafficRouting:
        {{ .Values.rollouts.ingressClassName }}:
          annotationPrefix: {{ .Values.ingress.canary.annotationPrefix }}
          {{- with .Values.ingress.canary.annotations }}
          additionalIngressAnnotations:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ingress: {{ .Values.ingress.name }}
          servicePort: {{ .Values.service.port }}
      steps:
      {{- with .Values.rollouts.steps -}}
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
