{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestSessionSecretKey: "{{ .Values.qTestSession.qTestSessionSecretKey }}"
  qTestSessionDBPWD: "{{ .Values.qTestSession.qTestSessionDBPwd }}"
kind: Secret
metadata:
  name: qtest-session-secret
type: Opaque
{{- end -}}
