{{- if and .Values.ingressClass.enabled (not .Values.ingressClass.existingclassName) }}
{{- if semverCompare ">=1.18" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end}}
kind: IngressClass
metadata:
  name: "{{ include "qtest-mgr.fullname" . }}-ingressclass"
  namespace: {{ .Values.namespace.name }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefaultClass | quote }}
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
spec:
  controller: {{ .Values.ingressClass.controller }}
{{- end }}
