{{- $existingImageCredentials := .Values.imageCredentials.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: mgr-liquibase-job
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.liquibase.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      name: mgr-liquibase-job
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: qtestliquibase
          image: "{{ .Values.image.liquibase }}:{{ .Values.image.liquibasetag }}"
          imagePullPolicy: {{ .Values.image.liquibasepullpolicy }}
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.5"
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-liquibase-config
                  key: client.jdbc.postgres.url
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: qtest-liquibase-config
                  key: client.jdbc.postgres.username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.secrets.existingConfigs }}
                  name: {{ .Values.secrets.existingConfigs }}
                  {{ else }}
                  name: qtest-manager-secret
                  {{- end }}
                  key: client.jdbc.postgres.password
          {{- if .Values.qTestManager.client.jdbc.sslEnable }}
          volumeMounts:
          - name: qtest-manager-secret-root-volume
            mountPath: {{ .Values.qTestManager.client.jdbc.sslMountPath }}
          {{- end }}
      restartPolicy: OnFailure
    {{ if .Values.imageCredentials.enabled }}
      {{ if .Values.imageCredentials.existingImageCredentials }}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{ else }}
      imagePullSecrets:
        - name: {{ $imageCredentials }}-liquibase
      {{- end }}
    {{- end }}
    {{- if .Values.qTestManager.client.jdbc.sslEnable }}
      volumes:
        - name: qtest-manager-secret-root-volume
          secret:
            secretName: qtest-db-root-secret
    {{- end }}
