{{- if .Values.workflow.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mgr-regression-
  {{- with .Values.workflow.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.workflow.adminModeNamespace }}
spec:
  entrypoint: mgr-regression
  podGC:  # Pod GC provides the ability to delete pods automatically without deleting the workflow.
    # OnWorkflowSuccess - delete pods when workflow is successful
    strategy: {{ .Values.workflow.podGC }}
  serviceAccountName: {{ .Values.workflow.serviceAccountName }}
  templates:
    - name: mgr-regression
      steps:
        - - name: run-api-test-1
            template: run-api-test-1
          - name: run-api-test-2
            template: run-api-test-2
          - name: run-api-test-3
            template: run-api-test-3
          - name: run-api-test-4
            template: run-api-test-4
    - name: run-api-test-1
      inputs:
        artifacts:
        - name: run-api-test-1
          path: /src
          git:
            repo: {{ .Values.workflow.postman.repo }}
            revision: {{ .Values.workflow.revision }}
            usernameSecret:
              name: {{ .Values.workflow.secret }}
              key: username
            passwordSecret:
              name: {{ .Values.workflow.secret }}
              key: password
      container:
        image: {{ .Values.workflow.postman.image }}
        command: [sh, -c]
        args: ["./postman/dev-run.sh smoketest1"]
        workingDir: /src

    - name: run-api-test-2
      inputs:
        artifacts:
        - name: run-api-test-2
          path: /src
          git:
            repo: {{ .Values.workflow.postman.repo }}
            revision: {{ .Values.workflow.revision }}
            usernameSecret:
              name: {{ .Values.workflow.secret }}
              key: username
            passwordSecret:
              name: {{ .Values.workflow.secret }}
              key: password
      container:
        image: {{ .Values.workflow.postman.image }}
        command: [sh, -c]
        args: ["./postman/dev-run.sh smoketest2"]
        workingDir: /src

    - name: run-api-test-3
      inputs:
        artifacts:
        - name: run-api-test-3
          path: /src
          git:
            repo: {{ .Values.workflow.postman.repo }}
            revision: {{ .Values.workflow.revision }}
            usernameSecret:
              name: {{ .Values.workflow.secret }}
              key: username
            passwordSecret:
              name: {{ .Values.workflow.secret }}
              key: password
      container:
        image: {{ .Values.workflow.postman.image }}
        command: [sh, -c]
        args: ["./postman/dev-run.sh smoketest3"]
        workingDir: /src

    - name: run-api-test-4
      inputs:
        artifacts:
        - name: run-api-test-4
          path: /src
          git:
            repo: {{ .Values.workflow.postman.repo }}
            revision: {{ .Values.workflow.revision }}
            usernameSecret:
              name: {{ .Values.workflow.secret }}
              key: username
            passwordSecret:
              name: {{ .Values.workflow.secret }}
              key: password
      container:
        image: {{ .Values.workflow.postman.image }}
        command: [sh, -c]
        args: ["./postman/dev-run.sh smoketest4"]
        workingDir: /src
{{- end }}
