{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qtest-mgr-resource-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    {{ .Values.resourceQuota.hard | toYaml | indent 4 | trim }}
{{- end }}
---
{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: qtest-mgr-limit-range
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
    {{ .Values.limitRange.limits | toYaml | indent 4 | trim }}
{{- end }}
