{{- if .Values.vpaAutoscaling.enabled }}
{{- if .Values.deployments.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: mgr-deployment
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-deployment-api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: mgr-deployment-api
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-deployment-poller
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: mgr-deployment-poller
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-deployment-notification
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: mgr-deployment-notification
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
{{- end }}
{{- if .Values.rollouts.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-rollout
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: mgr-rollout
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-api-rollout
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: mgr-api-rollout
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-poller-rollout
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: mgr-poller-rollout
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mgr-notification-rollout
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qtest-mgr.labels" . | nindent 4 }}
spec:
  targetRef: 
    apiVersion: "argoproj.io/v1alpha1"
    kind: Rollout
    name: mgr-notification-rollout
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode }}
{{- end }}
{{- end }}
