reloader:
  enabled: true
# deployment annotations
annotations:
  reloader.stakater.com/search: "true"
serviceAccount:
  name: qtest-mgr-sa
  create: true
  annotations:
    # Replace role ARN with your AWS Role with permissions in doc/README-EKS.md
    eks.amazonaws.com/role-arn: arn:aws:iam::accountnumber:role/

## create a secret called qtest-manager-secret before installing helm chart
secrets:
  enabled: true
  existingConfigs: qtest-manager-secret

## Set to true for private Tricentis dockerhub
imageCredentials:
  enabled: false
  # name: ""
  # registry: https://index.docker.io/v1/
  # username: ""
  # password: ""
  # email: ""
  # existingImageCredentials: ""
  
ingressClass:
  enabled: true
  # existingclassName:
  labels: {}
  controller: ingress.k8s.aws/alb

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Replace certificate
    alb.ingress.kubernetes.io/certificate-arn: <Cert ARN>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health-checker
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    host: qtest.svc.com
  paths: []
  extraPaths:
    - path: /*
      pathType: ImplementationSpecific
      backendServiceName: mgr-service
      backendPort: 8080
    - path: /*
      pathType: ImplementationSpecific
      backendServiceName: ssl-redirect
      backendPort: 8080

qTestManager:
  client:
    jdbc:
      postgresUrl: <Postgres_url>
      postgresUserName: <Postgres_user>
      postgresReadOnlyUrl: <Postgres_url-readonly>
      postgresReadOnlyUserName: <Postgres_user>
  elasticSearch:
    init: true
    disable: false
    scheme: https
    host: <ES Host>
    port: 443
  blobStorage:
    region: us-east-1
    sharedBucket: <storage bucket>
  s3:
    folder: qtest/manager
  preUrl: http://<sitename>.<domain> ## Example: http://<sitename>.tricentis.com
  preUrlHttps: https://<sitename>.<domain> ## Example: https://<sitename>.tricentis.com
  preSessionUrl: <Sessions url>
  pulseUrlBase: <Pulse url>
  insightsUrl: <Insights URL>
  launchUrlBase: <Launch URL>
  tdmSettingUrl: <Parameters URL>

persistence:
  enabled: false
