name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'Charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0       
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.4.0 #renovate: datasource=github-releases depName=helm/helm
      - name: Add external Helm repos
        run: helm repo add reloader https://stakater.github.io/stakater-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: Charts
          # version: v1.1.1 # renovate: datasource=github-releases depName=helm/chart-releaser
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'