apiVersion: v1
kind: ConfigMap
metadata:
  name: qtest-scenario-configmap
  namespace: {{ .Values.namespace.name }}
  labels:
    app: qTestScenario
data:
  qTestScenarioDBName: "{{ .Values.qTestScenario.qTestScenarioDBName }}"
  qTestScenarioDBUserName: "{{ .Values.qTestScenario.qTestScenarioDBUserName }}"
  qTestScenarioDBHostName: "{{ .Values.qTestScenario.qTestScenarioDBHostName }}"
  qTestScenarioLocalBaseURL: "{{ .Values.qTestScenario.qTestScenarioLocalBaseURL }}"
  qTestScenarioNodeTLSRejectUnAuthorized: "{{ .Values.qTestScenario.qTestScenarioNodeTLSRejectUnAuthorized }}"
  qTestScenarioNodeEnvironment : "{{ .Values.qTestScenario.qTestScenarioNodeEnvironment }}"
  qTestScenarioPort: "{{ .Values.qTestScenario.qTestScenarioPort }}"
  qTestScenarioAppKeyDescriptor: "{{ .Values.qTestScenario.qTestScenarioAppKeyDescriptor }}"
  qTestScenarioQTestURL: "{{ .Values.qTestScenario.qTestScenarioQTestURL }}"
