{{- $existingImageCredentials := .Values.imageCredentials.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
{{- $affinity := deepCopy (default (dict) .Values.affinity) | merge (.Values.deployment.singlePodPerNode | ternary (include "qtest-scenario.podAntiAffinity" . | fromYaml) (dict)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-scenario
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.rollouts.enabled }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-scenario
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: qtest-scenario
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
    {{ toYaml . | indent 8 }}
    {{- end }}
    {{ if .Values.imageCredentials.enabled }}
      {{ if .Values.imageCredentials.existingImageCredentials }}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{ else }}
      imagePullSecrets:
        - name: {{ $imageCredentials }}
      {{- end }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      initContainers:
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
{{- if .Values.extraArgs }}
          args:
{{- with .Values.extraArgs }}
{{ toYaml . | indent 12 }}
{{- end }}
{{- end }}
          livenessProbe:
          {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
            {{ .Values.livenessSslProbe | toYaml | indent 12 | trim }}
          {{- else }}
            {{ .Values.livenessProbe | toYaml | indent 12 | trim }}
          {{- end }}
          readinessProbe:
          {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
            {{ .Values.readinessSslProbe | toYaml | indent 12 | trim }}
          {{- else }}
            {{ .Values.readinessProbe | toYaml | indent 12 | trim }}
          {{- end }}
          startupProbe:
          {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
            {{ .Values.startupSslProbe | toYaml | indent 12 | trim }}
          {{- else }}
            {{ .Values.startupProbe | toYaml | indent 12 | trim }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
            - containerPort: {{ .Values.service.targetHttpsPort }}
              name: https
            {{- else }}
            - containerPort: {{ .Values.service.targetPort }}
              name: http
            {{- end }}
          env:
            - name: SCENARIO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBName
            - name: SCENARIO_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBUserName
            - name: SCENARIO_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: client.jdbc.postgres.password
            - name: SCENARIO_DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBHostName
            - name: SCENARIO_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBPort
            - name: DEPLOYMENT_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDeploymentEnv
            - name: DATABASE_URL
              {{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
              value: {{ printf "postgresql://$(SCENARIO_DB_USERNAME):$(SCENARIO_DB_PWD)@$(SCENARIO_DB_HOSTNAME):$(SCENARIO_DB_PORT)/$(SCENARIO_DB_NAME)%s" .Values.qTestScenario.qTestScenarioDBSSL }}
              {{- end }}
              {{- if not .Values.qTestScenario.qTestScenarioDBSSLEnable }}
              value: {{ printf "postgresql://$(SCENARIO_DB_USERNAME):$(SCENARIO_DB_PWD)@$(SCENARIO_DB_HOSTNAME):$(SCENARIO_DB_PORT)/$(SCENARIO_DB_NAME)" }}
              {{- end }}
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioPort
            - name: LOCAL_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioLocalBaseURL
            - name: SWAGGER_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioSwaggerUrl
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioNodeTLSRejectUnAuthorized
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioNodeEnvironment
            - name: QTEST_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioQTestURL
            - name: APP_KEY_FOR_DESCRIPTOR
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioAppKeyDescriptor
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: qtest-scenario-secret
                  key: qTestScenarioRefreshTokenSecret
            - name: SSL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioIsSSLRequired
          {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
            - name: SSL_CERT
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioSSLCert
            - name: SSL_KEY
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioSSLKey
          {{- end }}
{{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
          - name: qtest-scenario-logs
            mountPath: /root/.pm2/logs
        {{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
          - name: qtest-db-secret-volume
            mountPath: {{ .Values.qTestScenario.qTestScenarioDBSSLMountPath }}
        {{- end }}
        {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
          - name: qtest-scenario-secret-ssl-volume
            mountPath: {{ .Values.qTestScenario.qTestScenarioSSLMountPath }}
            readOnly: true
        {{- end }}
{{- with .Values.extraVolumeMounts }}
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: qtest-scenario-logs
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "qtest-scenario.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
        - name: qtest-db-secret-volume
          secret:
            secretName: qtest-db-root-secret
        {{- end }}
        {{- if .Values.qTestScenario.qTestScenarioSSLRequired }}
        - name: qtest-scenario-secret-ssl-volume
          secret:
            secretName: qtest-ssl-root-secret
        {{- end }}
{{- with .Values.extraVolumes }}
{{ toYaml . | indent 8 }}
{{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
