apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtest-scenario
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: qtest-scenario
  template:
    metadata:
      labels:
        app: qtest-scenario
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.autoscaling.healthApiPath }}
              port: {{ .Values.service.targetPort }}
            failureThreshold: {{ .Values.autoscaling.failureThreshold }}
            periodSeconds: {{ .Values.autoscaling.periodSeconds }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: SCENARIO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBName
            - name: SCENARIO_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBUserName
            - name: SCENARIO_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: client.jdbc.postgres.password
            - name: SCENARIO_DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioDBHostName
            - name: DATABASE_URL
              {{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
              value: {{ printf "postgresql://$(SCENARIO_DB_USERNAME):$(SCENARIO_DB_PWD)@$(SCENARIO_DB_HOSTNAME)/$(SCENARIO_DB_NAME)%s" .Values.qTestScenario.qTestScenarioDBSSL }}
              {{- end }}
              {{- if not .Values.qTestScenario.qTestScenarioDBSSLEnable }}
              value: {{ printf "postgresql://$(SCENARIO_DB_USERNAME):$(SCENARIO_DB_PWD)@$(SCENARIO_DB_HOSTNAME)/$(SCENARIO_DB_NAME)" }}
              {{- end }}
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioPort
            - name: LOCAL_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioLocalBaseURL
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioNodeTLSRejectUnAuthorized
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioNodeEnvironment
            - name: QTEST_URL
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioQTestURL
            - name: APP_KEY_FOR_DESCRIPTOR
              valueFrom:
                configMapKeyRef:
                  name: qtest-scenario-configmap
                  key: qTestScenarioAppKeyDescriptor
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: qtest-scenario-secret
                  key: qTestScenarioRefreshTokenSecret
{{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
          volumeMounts:
          - name: qtest-db-secret-volume
            mountPath: {{ .Values.qTestScenario.qTestScenarioDBSSLMountPath }}
      volumes:
      - name: qtest-db-secret-volume
        secret:
          secretName: qtest-db-root-secret
{{- end -}}
