{{- if .Values.ingress.enabled -}}
  {{- $serviceName := .Values.service.serviceName -}}
  {{- $servicePort := .Values.service.port -}}
  {{- $paths := .Values.ingress.paths -}}
  {{- $extraPaths := .Values.ingress.extraPaths -}}
{{- if semverCompare ">=1.18" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end}}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.labels }}
  labels:
  {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: "{{ include "qtest-scenario.fullname" . }}-ingressclass"
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- range $p := $extraPaths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.backend.service.name }}
                port:
                  number: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{ toYaml .Values.ingress.tls | indent 4 }}
    {{- end -}}
  {{- end -}}

