{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestScenarioRefreshTokenSecret: "{{ .Values.qTestScenario.qTestScenarioRefreshTokenSecret }}"
  qTestScenarioDBPWD: {{ .Values.qTestScenario.qTestScenarioDBPwd }}
kind: Secret
metadata:
  name: qtest-scenario-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
---
{{- if .Values.qTestScenario.qTestScenarioDBSSLEnable }}
apiVersion: v1
data:
  root.crt: "{{ .Values.qTestScenario.qTestScenarioDBCRT }}"
kind: Secret
metadata:
  name: qtest-scenario-root-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
{{- end -}}
{{- end -}}
