{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestScenarioRefreshTokenSecret: "{{ .Values.qTestScenario.qTestScenarioRefreshTokenSecret }}"
kind: Secret
metadata:
  name: qtest-scenario-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
{{- end -}}
