{{- if and .Values.secrets.enabled (not .Values.secrets.existingConfigs) }}
apiVersion: v1
data:
  qTestScenarioRefreshTokenSecret: "{{ .Values.qTestScenario.qTestScenarioRefreshTokenSecret }}"
  qTestScenarioDBPWD: {{ .Values.qTestScenario.qTestScenarioDBPwd }}
kind: Secret
metadata:
  name: qtest-scenario-secret
type: Opaque
{{- end -}}
